---
- name: "Lab 02 Bucles"
  hosts: nodo02
  vars:
    archivos:
      - arch_01
      - arch_02
      - arch_03
      - arch_04
      - arch_05
    paquetes:
      - zip
      - unzip
      - gzip
      - bzip2 
    ruta1: "/tmp/archivos_lab02/"
    ruta2: "/mnt/disco02/"
  vars_files:
    "vars/defaults.yml"
  tasks:
    - name: "Instalar paquetes"        
      yum:
        name: "{{ item }}"
        state: present
      loop: "{{ paquetes }}"

    - name: "Crear {{ ruta1 }}"
      file:
        path: "{{ ruta1 }}"
        state: directory
        mode: 0655

    - name: "Crear archivos en {{ ruta1 }}"
      file:
        path: "{{ ruta1 }}{{ item }}"
        state: touch
        mode: 0655
      loop: "{{ archivos }}"
# En adelante copiado de Evan 
    - name: "Crea la partici칩n"
      parted:
        device: "{{ item.value['dispositivo'] }}"
        number: 1
        flags: [ lvm ]
        state: present
      loop: "{{ discos|dict2items }}"
      # Comprobar con lsblk (debe aparecer una particion sdb1 y sdc1)

    - name: "Crea el grupo de volumenes"
      lvg:
        vg: "{{ item.value['volum_group'] }}"
        pvs: "{{ item.value['volumen_fisico'] }}"
        pesize: "{{ item.value['tama침o_vg'] }}"
      loop: "{{ discos|dict2items }}"
      # Comprobar con pvs (debe aparecer el VG creado)

    - name: "Crea el volumen logico"
      lvol:
        vg: "{{ item.value['volum_group'] }}"
        lv: "lv_{{ item.value['volum_group'] }}"
        size: "{{ item.value['tama침o_lv'] }}"
        resizefs: true
        force: yes
        state: present
      loop: "{{ discos|dict2items }}"
      # Falla con tama침o_lv: "80%VG"
      # Comprobar con lvdisplay

    - name: "Configura el sistema de ficheros"
      filesystem:
        fstype: "{{ item.value['formato_fs'] }}"
        dev: "/dev/mapper/{{ item.value['volum_group'] }}-lv_{{ item.value['volum_group'] }}"
      loop: "{{ discos|dict2items }}"
      # Comprobar con lvdisplay

    - name: "Crea la ruta de montaje"
      file:
        path: "{{ item.value['punto_montaje'] }}"
        mode: 0765
        recurse: yes
        state: directory
      loop: "{{ discos|dict2items }}"

    - name: "Monta el sistema de ficheros"
      mount:
        path: "{{ item.value['punto_montaje'] }}"
        src: "/dev/mapper/{{ item.value['volum_group'] }}-lv_{{ item.value['volum_group'] }}"
        fstype: "{{ item.value['formato_fs'] }}"
        state: mounted
      loop: "{{ discos|dict2items }}"
      # Comprobar con lvdisplay
    
    - name: "Comprime todos los archivos en {{ ruta1 }} con zip y lo deja en el directorio {{ ruta2 }}"
      archive:
        path: "{{ ruta1 }}"
        dest: "{{ ruta2 }}archivos_lab02.zip"
        format: zip
        # Listar el contenido:
        # zip -sf archivo.zip
...